// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: order-service.proto

package ordersservice

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _order_service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AddOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddOrderReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddOrderReqMultiError, or
// nil if none found.
func (m *AddOrderReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddOrderReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = AddOrderReqValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddOrderReq_UserRole_InLookup[m.GetUserRole()]; !ok {
		err := AddOrderReqValidationError{
			field:  "UserRole",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetTargetUrl()); err != nil {
		err = AddOrderReqValidationError{
			field:  "TargetUrl",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := AddOrderReqValidationError{
			field:  "TargetUrl",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddOrderReq_OrderType_InLookup[m.GetOrderType()]; !ok {
		err := AddOrderReqValidationError{
			field:  "OrderType",
			reason: "value must be in list [comments likes views]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetQuantity() <= 0 {
		err := AddOrderReqValidationError{
			field:  "Quantity",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetServiceUrl()); err != nil {
		err = AddOrderReqValidationError{
			field:  "ServiceUrl",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := AddOrderReqValidationError{
			field:  "ServiceUrl",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddOrderReqMultiError(errors)
	}

	return nil
}

func (m *AddOrderReq) _validateUuid(uuid string) error {
	if matched := _order_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AddOrderReqMultiError is an error wrapping multiple validation errors
// returned by AddOrderReq.ValidateAll() if the designated constraints aren't met.
type AddOrderReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddOrderReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddOrderReqMultiError) AllErrors() []error { return m }

// AddOrderReqValidationError is the validation error returned by
// AddOrderReq.Validate if the designated constraints aren't met.
type AddOrderReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddOrderReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddOrderReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddOrderReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddOrderReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddOrderReqValidationError) ErrorName() string { return "AddOrderReqValidationError" }

// Error satisfies the builtin error interface
func (e AddOrderReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddOrderReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddOrderReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddOrderReqValidationError{}

var _AddOrderReq_UserRole_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

var _AddOrderReq_OrderType_InLookup = map[string]struct{}{
	"comments": {},
	"likes":    {},
	"views":    {},
}

// Validate checks the field values on AddOrderRes with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddOrderRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddOrderRes with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddOrderResMultiError, or
// nil if none found.
func (m *AddOrderRes) ValidateAll() error {
	return m.validate(true)
}

func (m *AddOrderRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AddOrderResValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddOrderResMultiError(errors)
	}

	return nil
}

func (m *AddOrderRes) _validateUuid(uuid string) error {
	if matched := _order_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AddOrderResMultiError is an error wrapping multiple validation errors
// returned by AddOrderRes.ValidateAll() if the designated constraints aren't met.
type AddOrderResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddOrderResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddOrderResMultiError) AllErrors() []error { return m }

// AddOrderResValidationError is the validation error returned by
// AddOrderRes.Validate if the designated constraints aren't met.
type AddOrderResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddOrderResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddOrderResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddOrderResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddOrderResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddOrderResValidationError) ErrorName() string { return "AddOrderResValidationError" }

// Error satisfies the builtin error interface
func (e AddOrderResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddOrderRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddOrderResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddOrderResValidationError{}

// Validate checks the field values on OrderInfoReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderInfoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderInfoReqMultiError, or
// nil if none found.
func (m *OrderInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = OrderInfoReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = OrderInfoReqValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderInfoReqMultiError(errors)
	}

	return nil
}

func (m *OrderInfoReq) _validateUuid(uuid string) error {
	if matched := _order_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderInfoReqMultiError is an error wrapping multiple validation errors
// returned by OrderInfoReq.ValidateAll() if the designated constraints aren't met.
type OrderInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderInfoReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderInfoReqMultiError) AllErrors() []error { return m }

// OrderInfoReqValidationError is the validation error returned by
// OrderInfoReq.Validate if the designated constraints aren't met.
type OrderInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderInfoReqValidationError) ErrorName() string { return "OrderInfoReqValidationError" }

// Error satisfies the builtin error interface
func (e OrderInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderInfoReqValidationError{}

// Validate checks the field values on OrderInfoRes with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderInfoRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderInfoRes with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderInfoResMultiError, or
// nil if none found.
func (m *OrderInfoRes) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderInfoRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = OrderInfoResValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _OrderInfoRes_UserRole_InLookup[m.GetUserRole()]; !ok {
		err := OrderInfoResValidationError{
			field:  "UserRole",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _OrderInfoRes_Status_InLookup[m.GetStatus()]; !ok {
		err := OrderInfoResValidationError{
			field:  "Status",
			reason: "value must be in list [done cancelled processing]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetTargetUrl()); err != nil {
		err = OrderInfoResValidationError{
			field:  "TargetUrl",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := OrderInfoResValidationError{
			field:  "TargetUrl",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetServiceUrl()); err != nil {
		err = OrderInfoResValidationError{
			field:  "ServiceUrl",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := OrderInfoResValidationError{
			field:  "ServiceUrl",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _OrderInfoRes_OrderType_InLookup[m.GetOrderType()]; !ok {
		err := OrderInfoResValidationError{
			field:  "OrderType",
			reason: "value must be in list [comments likes views]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCreatedAt() == nil {
		err := OrderInfoResValidationError{
			field:  "CreatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUpdatedAt() == nil {
		err := OrderInfoResValidationError{
			field:  "UpdatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderInfoResMultiError(errors)
	}

	return nil
}

func (m *OrderInfoRes) _validateUuid(uuid string) error {
	if matched := _order_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderInfoResMultiError is an error wrapping multiple validation errors
// returned by OrderInfoRes.ValidateAll() if the designated constraints aren't met.
type OrderInfoResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderInfoResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderInfoResMultiError) AllErrors() []error { return m }

// OrderInfoResValidationError is the validation error returned by
// OrderInfoRes.Validate if the designated constraints aren't met.
type OrderInfoResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderInfoResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderInfoResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderInfoResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderInfoResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderInfoResValidationError) ErrorName() string { return "OrderInfoResValidationError" }

// Error satisfies the builtin error interface
func (e OrderInfoResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderInfoRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderInfoResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderInfoResValidationError{}

var _OrderInfoRes_UserRole_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

var _OrderInfoRes_Status_InLookup = map[string]struct{}{
	"done":       {},
	"cancelled":  {},
	"processing": {},
}

var _OrderInfoRes_OrderType_InLookup = map[string]struct{}{
	"comments": {},
	"likes":    {},
	"views":    {},
}

// Validate checks the field values on DelOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DelOrderReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DelOrderReqMultiError, or
// nil if none found.
func (m *DelOrderReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DelOrderReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = DelOrderReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = DelOrderReqValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _DelOrderReq_Role_InLookup[m.GetRole()]; !ok {
		err := DelOrderReqValidationError{
			field:  "Role",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DelOrderReqMultiError(errors)
	}

	return nil
}

func (m *DelOrderReq) _validateUuid(uuid string) error {
	if matched := _order_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DelOrderReqMultiError is an error wrapping multiple validation errors
// returned by DelOrderReq.ValidateAll() if the designated constraints aren't met.
type DelOrderReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelOrderReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelOrderReqMultiError) AllErrors() []error { return m }

// DelOrderReqValidationError is the validation error returned by
// DelOrderReq.Validate if the designated constraints aren't met.
type DelOrderReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelOrderReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelOrderReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelOrderReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelOrderReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelOrderReqValidationError) ErrorName() string { return "DelOrderReqValidationError" }

// Error satisfies the builtin error interface
func (e DelOrderReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelOrderReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelOrderReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelOrderReqValidationError{}

var _DelOrderReq_Role_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

// Validate checks the field values on DelOrderRes with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DelOrderRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelOrderRes with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DelOrderResMultiError, or
// nil if none found.
func (m *DelOrderRes) ValidateAll() error {
	return m.validate(true)
}

func (m *DelOrderRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DelOrderResMultiError(errors)
	}

	return nil
}

// DelOrderResMultiError is an error wrapping multiple validation errors
// returned by DelOrderRes.ValidateAll() if the designated constraints aren't met.
type DelOrderResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelOrderResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelOrderResMultiError) AllErrors() []error { return m }

// DelOrderResValidationError is the validation error returned by
// DelOrderRes.Validate if the designated constraints aren't met.
type DelOrderResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelOrderResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelOrderResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelOrderResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelOrderResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelOrderResValidationError) ErrorName() string { return "DelOrderResValidationError" }

// Error satisfies the builtin error interface
func (e DelOrderResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelOrderRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelOrderResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelOrderResValidationError{}
