// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user-service.proto

package userservice

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _user_service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RegReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RegReqMultiError, or nil if none found.
func (m *RegReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RegReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 2 || l > 50 {
		err := RegReqValidationError{
			field:  "Name",
			reason: "value length must be between 2 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = RegReqValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _RegReq_Role_InLookup[m.GetRole()]; !ok {
		err := RegReqValidationError{
			field:  "Role",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 8 {
		err := RegReqValidationError{
			field:  "Password",
			reason: "value length must be at least 8 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegReqMultiError(errors)
	}

	return nil
}

func (m *RegReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *RegReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// RegReqMultiError is an error wrapping multiple validation errors returned by
// RegReq.ValidateAll() if the designated constraints aren't met.
type RegReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegReqMultiError) AllErrors() []error { return m }

// RegReqValidationError is the validation error returned by RegReq.Validate if
// the designated constraints aren't met.
type RegReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegReqValidationError) ErrorName() string { return "RegReqValidationError" }

// Error satisfies the builtin error interface
func (e RegReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegReqValidationError{}

var _RegReq_Role_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

// Validate checks the field values on RegRes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegRes with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RegResMultiError, or nil if none found.
func (m *RegRes) ValidateAll() error {
	return m.validate(true)
}

func (m *RegRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 100 {
		err := RegResValidationError{
			field:  "Token",
			reason: "value length must be at least 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetSessionKey()); err != nil {
		err = RegResValidationError{
			field:  "SessionKey",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegResMultiError(errors)
	}

	return nil
}

func (m *RegRes) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RegResMultiError is an error wrapping multiple validation errors returned by
// RegRes.ValidateAll() if the designated constraints aren't met.
type RegResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegResMultiError) AllErrors() []error { return m }

// RegResValidationError is the validation error returned by RegRes.Validate if
// the designated constraints aren't met.
type RegResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegResValidationError) ErrorName() string { return "RegResValidationError" }

// Error satisfies the builtin error interface
func (e RegResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegResValidationError{}

// Validate checks the field values on LogReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LogReqMultiError, or nil if none found.
func (m *LogReq) ValidateAll() error {
	return m.validate(true)
}

func (m *LogReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 2 || l > 50 {
		err := LogReqValidationError{
			field:  "Name",
			reason: "value length must be between 2 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = LogReqValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 8 {
		err := LogReqValidationError{
			field:  "Password",
			reason: "value length must be at least 8 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LogReqMultiError(errors)
	}

	return nil
}

func (m *LogReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *LogReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// LogReqMultiError is an error wrapping multiple validation errors returned by
// LogReq.ValidateAll() if the designated constraints aren't met.
type LogReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogReqMultiError) AllErrors() []error { return m }

// LogReqValidationError is the validation error returned by LogReq.Validate if
// the designated constraints aren't met.
type LogReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogReqValidationError) ErrorName() string { return "LogReqValidationError" }

// Error satisfies the builtin error interface
func (e LogReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogReqValidationError{}

// Validate checks the field values on LogRes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogRes with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LogResMultiError, or nil if none found.
func (m *LogRes) ValidateAll() error {
	return m.validate(true)
}

func (m *LogRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 100 {
		err := LogResValidationError{
			field:  "Token",
			reason: "value length must be at least 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetSessionKey()); err != nil {
		err = LogResValidationError{
			field:  "SessionKey",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LogResMultiError(errors)
	}

	return nil
}

func (m *LogRes) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// LogResMultiError is an error wrapping multiple validation errors returned by
// LogRes.ValidateAll() if the designated constraints aren't met.
type LogResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogResMultiError) AllErrors() []error { return m }

// LogResValidationError is the validation error returned by LogRes.Validate if
// the designated constraints aren't met.
type LogResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogResValidationError) ErrorName() string { return "LogResValidationError" }

// Error satisfies the builtin error interface
func (e LogResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogResValidationError{}

// Validate checks the field values on ExtJWTDataReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExtJWTDataReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExtJWTDataReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExtJWTDataReqMultiError, or
// nil if none found.
func (m *ExtJWTDataReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ExtJWTDataReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 100 {
		err := ExtJWTDataReqValidationError{
			field:  "Token",
			reason: "value length must be at least 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetSessionKey()); err != nil {
		err = ExtJWTDataReqValidationError{
			field:  "SessionKey",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ExtJWTDataReqMultiError(errors)
	}

	return nil
}

func (m *ExtJWTDataReq) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ExtJWTDataReqMultiError is an error wrapping multiple validation errors
// returned by ExtJWTDataReq.ValidateAll() if the designated constraints
// aren't met.
type ExtJWTDataReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtJWTDataReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtJWTDataReqMultiError) AllErrors() []error { return m }

// ExtJWTDataReqValidationError is the validation error returned by
// ExtJWTDataReq.Validate if the designated constraints aren't met.
type ExtJWTDataReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtJWTDataReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtJWTDataReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtJWTDataReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtJWTDataReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtJWTDataReqValidationError) ErrorName() string { return "ExtJWTDataReqValidationError" }

// Error satisfies the builtin error interface
func (e ExtJWTDataReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtJWTDataReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtJWTDataReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtJWTDataReqValidationError{}

// Validate checks the field values on ExtJWTDataRes with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExtJWTDataRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExtJWTDataRes with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExtJWTDataResMultiError, or
// nil if none found.
func (m *ExtJWTDataRes) ValidateAll() error {
	return m.validate(true)
}

func (m *ExtJWTDataRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _ExtJWTDataRes_Role_InLookup[m.GetRole()]; !ok {
		err := ExtJWTDataResValidationError{
			field:  "Role",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for UserId

	if utf8.RuneCountInString(m.GetToken()) < 100 {
		err := ExtJWTDataResValidationError{
			field:  "Token",
			reason: "value length must be at least 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ExtJWTDataResMultiError(errors)
	}

	return nil
}

// ExtJWTDataResMultiError is an error wrapping multiple validation errors
// returned by ExtJWTDataRes.ValidateAll() if the designated constraints
// aren't met.
type ExtJWTDataResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtJWTDataResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtJWTDataResMultiError) AllErrors() []error { return m }

// ExtJWTDataResValidationError is the validation error returned by
// ExtJWTDataRes.Validate if the designated constraints aren't met.
type ExtJWTDataResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtJWTDataResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtJWTDataResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtJWTDataResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtJWTDataResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtJWTDataResValidationError) ErrorName() string { return "ExtJWTDataResValidationError" }

// Error satisfies the builtin error interface
func (e ExtJWTDataResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtJWTDataRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtJWTDataResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtJWTDataResValidationError{}

var _ExtJWTDataRes_Role_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

// Validate checks the field values on DelUserReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DelUserReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelUserReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DelUserReqMultiError, or
// nil if none found.
func (m *DelUserReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DelUserReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _DelUserReq_Role_InLookup[m.GetRole()]; !ok {
		err := DelUserReqValidationError{
			field:  "Role",
			reason: "value must be in list [admin dev guest]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = DelUserReqValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DelUserId

	if err := m._validateUuid(m.GetSessionKey()); err != nil {
		err = DelUserReqValidationError{
			field:  "SessionKey",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DelUserReqMultiError(errors)
	}

	return nil
}

func (m *DelUserReq) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DelUserReqMultiError is an error wrapping multiple validation errors
// returned by DelUserReq.ValidateAll() if the designated constraints aren't met.
type DelUserReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelUserReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelUserReqMultiError) AllErrors() []error { return m }

// DelUserReqValidationError is the validation error returned by
// DelUserReq.Validate if the designated constraints aren't met.
type DelUserReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelUserReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelUserReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelUserReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelUserReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelUserReqValidationError) ErrorName() string { return "DelUserReqValidationError" }

// Error satisfies the builtin error interface
func (e DelUserReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelUserReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelUserReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelUserReqValidationError{}

var _DelUserReq_Role_InLookup = map[string]struct{}{
	"admin": {},
	"dev":   {},
	"guest": {},
}

// Validate checks the field values on DelUserRes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DelUserRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DelUserRes with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DelUserResMultiError, or
// nil if none found.
func (m *DelUserRes) ValidateAll() error {
	return m.validate(true)
}

func (m *DelUserRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DelUserResMultiError(errors)
	}

	return nil
}

// DelUserResMultiError is an error wrapping multiple validation errors
// returned by DelUserRes.ValidateAll() if the designated constraints aren't met.
type DelUserResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DelUserResMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DelUserResMultiError) AllErrors() []error { return m }

// DelUserResValidationError is the validation error returned by
// DelUserRes.Validate if the designated constraints aren't met.
type DelUserResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DelUserResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DelUserResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DelUserResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DelUserResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DelUserResValidationError) ErrorName() string { return "DelUserResValidationError" }

// Error satisfies the builtin error interface
func (e DelUserResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDelUserRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DelUserResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DelUserResValidationError{}
