// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: user-service.proto

package userservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_HashPswd_FullMethodName   = "/users.UserService/HashPswd"
	UserService_RegUser_FullMethodName    = "/users.UserService/RegUser"
	UserService_LogUser_FullMethodName    = "/users.UserService/LogUser"
	UserService_ExtJWTData_FullMethodName = "/users.UserService/ExtJWTData"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	HashPswd(ctx context.Context, in *HashReq, opts ...grpc.CallOption) (*HashRes, error)
	RegUser(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error)
	LogUser(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRes, error)
	ExtJWTData(ctx context.Context, in *ExtJWTDataReq, opts ...grpc.CallOption) (*ExtJWTDataRes, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) HashPswd(ctx context.Context, in *HashReq, opts ...grpc.CallOption) (*HashRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashRes)
	err := c.cc.Invoke(ctx, UserService_HashPswd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegUser(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegRes)
	err := c.cc.Invoke(ctx, UserService_RegUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LogUser(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogRes)
	err := c.cc.Invoke(ctx, UserService_LogUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ExtJWTData(ctx context.Context, in *ExtJWTDataReq, opts ...grpc.CallOption) (*ExtJWTDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtJWTDataRes)
	err := c.cc.Invoke(ctx, UserService_ExtJWTData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	HashPswd(context.Context, *HashReq) (*HashRes, error)
	RegUser(context.Context, *RegReq) (*RegRes, error)
	LogUser(context.Context, *LogReq) (*LogRes, error)
	ExtJWTData(context.Context, *ExtJWTDataReq) (*ExtJWTDataRes, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) HashPswd(context.Context, *HashReq) (*HashRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HashPswd not implemented")
}
func (UnimplementedUserServiceServer) RegUser(context.Context, *RegReq) (*RegRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegUser not implemented")
}
func (UnimplementedUserServiceServer) LogUser(context.Context, *LogReq) (*LogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogUser not implemented")
}
func (UnimplementedUserServiceServer) ExtJWTData(context.Context, *ExtJWTDataReq) (*ExtJWTDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtJWTData not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_HashPswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HashPswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HashPswd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HashPswd(ctx, req.(*HashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RegUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegUser(ctx, req.(*RegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LogUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LogUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LogUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LogUser(ctx, req.(*LogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ExtJWTData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtJWTDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ExtJWTData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ExtJWTData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ExtJWTData(ctx, req.(*ExtJWTDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HashPswd",
			Handler:    _UserService_HashPswd_Handler,
		},
		{
			MethodName: "RegUser",
			Handler:    _UserService_RegUser_Handler,
		},
		{
			MethodName: "LogUser",
			Handler:    _UserService_LogUser_Handler,
		},
		{
			MethodName: "ExtJWTData",
			Handler:    _UserService_ExtJWTData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}
